### ISSUE TITLE
Hur bygger man detta?

### ISSUE THREAD

**Issue by Ricardicus** [jomag/stuga2020#6]
Vill bygga på min dator och spela #stuga! 
Skulle du kunna lägga in en README eller något där du 
förklarar för en lekman hur man sätter upp det? 
Ser ut att vara ett javascript projekt.
Vilka os funkar det på? 

Ha det gött.

Why did I leave the plow in the field, and look for a job in the town.
// Rickard

**Comment by jomag** [comment]
Hej!

Mycket riktigt, BASIC-tolken ([jomag/bajsic](https://github.com/jomag/bajsic)) är skriven i JavaScript, så du behöver ha en rimlig version av [NodeJS](https://nodejs.org) installerad. Därefter är det kortfattat följande du behöver köra:

```bash
$ git clone git@github.com:jomag/bajsic
$ git clone git@github.com:jomag/stuga2020
$ cd bajsic
$ npm install
$ npm run ../stuga2020/stuga/stuga.bas
```

Mycket nöje 😁

**Comment by Ricardicus** [comment]
Spännande :) Tack!

**Comment by Ricardicus** [comment]
Jag stöter på lite problem. Det kan bero på att jag inte har en aning om vad jag sysslar med, så ha det i åtanke.

```
➜  bajsic git:(master) node --version
v12.18.4
➜  bajsic git:(master) npm install
npm WARN bajsic@0.0.1 No repository field.

audited 343 packages in 6.332s
found 33 vulnerabilities (28 low, 2 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
➜  bajsic git:(master) npm start ../stuga2020/stuga/stuga.bas     

> bajsic@0.0.1 start /home/riha/dev/garage/github/bajsic
> node -r esm src/cli.js "../stuga2020/stuga/stuga.bas"

] 
```

När prompten kommit såhär långt, får jag fel varje gång jag skriver in något..
Nu chansar jag t.ex. och skriver "help", då ser det såhär ut:

```
> bajsic@0.0.1 start /home/riha/dev/garage/github/bajsic
> node -r esm src/cli.js "../stuga2020/stuga/stuga.bas"

] help
SyntaxError: Expected token with type eq at end of line
    at popType (/home/riha/dev/garage/github/bajsic/src/parser/utils.js:38:11)
    at parseLet (/home/riha/dev/garage/github/bajsic/src/parser/index.js:96:29)
    at parsePrimaryStatement (/home/riha/dev/garage/github/bajsic/src/parser/index.js:224:16)
    at parseStatement (/home/riha/dev/garage/github/bajsic/src/parser/index.js:233:19)
    at parseStatements (/home/riha/dev/garage/github/bajsic/src/parser/index.js:262:23)
    at parseLine (/home/riha/dev/garage/github/bajsic/src/parser/index.js:300:23)
    at shell (/home/riha/dev/garage/github/bajsic/src/shell.js:41:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'help',
  lineNumber: undefined
}
Expected token with type eq at end of line

] 

```

**Comment by jomag** [comment]
Skriv `RUN` vid prompten.

**Comment by Ricardicus** [comment]
Gött!! Nu funkar det.

```
               IIIIIIIIIIIIIIII
   _ _ _      II              II      _ _ _
__I I I I_____I                I_____I I I I______
  I I I I     I   I--I  I--I   I     I I I I
  I_I_I_I     I   I  I  I  I   I     I_I_I_I
              I   I  I  I  I   I    
              I   I *I  I* I   I
              I   I__I  I__I   I
              II              II
               II            II
                II          II
                 I__      __I
                    I    I
                    I    I
                    I    I
                    I    I
                    II  II
                     I__I
Välkommen till VIOLs stuga!!!!!
Har du vågat dej in här förut? 
```

**Comment by Ricardicus** [comment]
Har du källkoden för stugan.org? 
Vill bidra genom att bygga en kontainer för den i docker :)

**Comment by jomag** [comment]
Källkoden är detta repo ;)

**Comment by Ricardicus** [comment]
Ok, men hur startar jag då servern? 

```
npm start ../stuga2020/stuga/stuga.bas
```

Startar ju igång basic översättaren. 
Men hela web-gui grejen med xterm osv, 
hur startar jag den?

**Comment by jomag** [comment]
Aha. Det är en standard React app, så:

```
git clone github.com:jomag/stuga2020
cd stuga2020
npm install
npm start
```

**Comment by Ricardicus** [comment]
Fantastiskt! 

Tack. Jag kommer nog med en pull request snart, med en dockerfile, så man kan köra ditt superfina projekt i en kontainer.
Du är helt fri att totalt ignorera den. Men nu får du en förvarning! :D
